@Restaurants.API_HostAddress = http://localhost:5232

@token=CfDJ8HmU2UI85UpGm3s7AjERtKDgmKc25naVYcFkPXA9NizltUn3nihQndFqxZktQaPb6ScQmTeeVVmJKgnmi7AOW0kIZ6seGAuOU3dsasu_Nso4AWEg4_YQhpv9cWvrT52CVkrLX5HknezWu2hjf52uhAu6qJ5RtD5Zkw_suoOvklI2gHlwfi-l-OqflEDdE6gPH9y683_Ts_YpfhnWJRko3yvhH9Y9ISLS_mGToxg4xri2V6Y67qEP6FvZhfh3MTtQDxgsGHc7uF_kYquHyUOy_S5l4ARqCp75SydqmyztllmZfRsrjfTmT3w3FKPPrV46ROZFHxWbnQhwXKRi2zUlJzDkmHHo9Ef3VQWYisiGaqRFw3LbK4Y3Rn1qnMQc2MW3o1rGq1ES5N1BNJFqnkF71-EmTnvQqvt3Sifw9nurDBAkHtPtYjWkrMYla6MbuRgBWeKhQc0bkR0uTI4NnMtTrpNYpIzczVcH8lU-y_NdbRCu1ZpNy2q201CY0K1NJxzy1-c6FS6eKc5l5_822YfHj8oKhSopND7t_O03ISJZYLGOzyDV6oCHaqDvhLxaprgeSivwqDAAZUBHMewZdBVu-QvxTiTlvyR7PHVE1RNNx6VUi0vXVfAzJK4o0CNxKYYrXK-9u2SNzH9duoksFyRJGflC7fiHbvEX3w9akHSHYrNlKgJyNs9jaKcEqBYScM8rwQ
GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
###
GET {{Restaurants.API_HostAddress}}/api/restaurants/3

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/3


###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
   "Name": "Tasty Tests2",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

PUT {{Restaurants.API_HostAddress}}/api/restaurants/6
Content-Type: application/json

{
  "Name": "Sample patch2",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": false
}
###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1099


###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Password1!"
}

###